module.exports = {
    IPFS_GATEWAY: process.env.IPFS_GATEWAY,
    IPFS_API: process.env.IPFS_API,

    ETH_CHAINID: process.env.ETHEREUM_CHAINID,
    CONTRACT_ADDRESS: process.env.CONTRACT_ADDRESS,
    ETHEREUM_TOKEN_URL_TEMPLATE: process.env.ETHEREUM_TOKEN_URL_TEMPLATE,
}
